"""revised_table

Revision ID: a50b248ea467
Revises: 
Create Date: 2025-09-10 06:55:22.855598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a50b248ea467'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('faqs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question', sa.String(length=255), nullable=True),
    sa.Column('answer', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file_downloads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('logo', sa.String(length=1000), nullable=True),
    sa.Column('website_link', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('current_plan', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=False)
    op.create_table('super_admin',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('llm_model_name', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_super_admin_llm_model_name'), 'super_admin', ['llm_model_name'], unique=False)
    op.create_table('user_guide',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video_tutorials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chatbot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chatbot_name', sa.String(length=250), nullable=False),
    sa.Column('chatbot_type', sa.String(length=250), nullable=False),
    sa.Column('specialized_type', sa.Enum('internal', 'student', 'external', name='bottype', native_enum=False), nullable=True),
    sa.Column('scaffolding_level', sa.Enum('low', 'medium', 'high', name='scaffoldinglevel', native_enum=False), nullable=True),
    sa.Column('llm_model_name', sa.String(length=250), nullable=False),
    sa.Column('llm_temperature', sa.Numeric(precision=2, scale=2), nullable=False),
    sa.Column('llm_prompt', sa.Text(), nullable=False),
    sa.Column('llm_role', sa.String(length=100), nullable=False),
    sa.Column('llm_streaming', sa.Boolean(), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('prompt_status', sa.String(length=100), nullable=True),
    sa.Column('memory_status', sa.Boolean(), nullable=True),
    sa.Column('total_chatbot_messages_count', sa.Integer(), nullable=False),
    sa.Column('admin_per_days_messages_count', sa.Integer(), nullable=True),
    sa.Column('per_day_messages', sa.Integer(), nullable=True),
    sa.Column('public_per_day_messages_count', sa.Integer(), nullable=True),
    sa.Column('public_last_7_days_messages', sa.JSON(), nullable=True),
    sa.Column('monthly_messages_count', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatbot_chatbot_name'), 'chatbot', ['chatbot_name'], unique=False)
    op.create_index(op.f('ix_chatbot_chatbot_type'), 'chatbot', ['chatbot_type'], unique=False)
    op.create_index(op.f('ix_chatbot_llm_model_name'), 'chatbot', ['llm_model_name'], unique=False)
    op.create_index(op.f('ix_chatbot_prompt_status'), 'chatbot', ['prompt_status'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('building', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('should_live_on_marti_page', sa.Boolean(), nullable=False),
    sa.Column('should_live_on_marti_agent', sa.Boolean(), nullable=False),
    sa.Column('marti_agent_review', sa.Boolean(), nullable=False),
    sa.Column('marti_website_review', sa.Boolean(), nullable=False),
    sa.Column('is_rejected_marti_website', sa.Boolean(), nullable=True),
    sa.Column('is_rejected_marti_agent', sa.Boolean(), nullable=True),
    sa.Column('admin_event_review', sa.Boolean(), nullable=True),
    sa.Column('user_response_to_review', sa.Boolean(), nullable=True),
    sa.Column('is_seen', sa.Boolean(), nullable=True),
    sa.Column('additional', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_table('rbac',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('form_submission', sa.Boolean(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rbac_id'), 'rbac', ['id'], unique=False)
    op.create_table('securityandlogs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('logs_type', sa.String(length=1000), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('dated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(length=1000), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'USER', 'SUPER_ADMIN', name='userrole', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('is_onboarded', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_walkthrough_completed', sa.Boolean(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('group_ids', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('total_messages', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('billing_cycle_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('billing_cycle_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_plan', sa.Enum('free', 'starter', 'enterprise', name='plan', native_enum=False), nullable=True),
    sa.Column('add_on_features', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('stripeId', sa.String(length=200), nullable=True),
    sa.Column('is_user_consent_given', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('bubble_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chatbot_id', sa.Integer(), nullable=False),
    sa.Column('bubble_bgColor', sa.String(length=250), nullable=True),
    sa.Column('bubble_icon', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['chatbot_id'], ['chatbot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bubble_settings_chatbot_id'), 'bubble_settings', ['chatbot_id'], unique=False)
    op.create_table('chatbot_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chatbot_id', sa.Integer(), nullable=False),
    sa.Column('url_sweep_option', sa.Enum('Domain', 'website_page', name='urlsweep', native_enum=False), nullable=False),
    sa.Column('document_name', sa.String(length=2000), nullable=True),
    sa.Column('content_type', sa.String(length=250), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('consumed_webscrap_quota_kb', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chatbot_id'], ['chatbot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chatbot_id_document_name', 'chatbot_documents', ['chatbot_id', 'document_name'], unique=False)
    op.create_index('idx_chatbot_id_document_name_status', 'chatbot_documents', ['chatbot_id', 'document_name', 'status'], unique=False)
    op.create_index(op.f('ix_chatbot_documents_content_type'), 'chatbot_documents', ['content_type'], unique=False)
    op.create_index(op.f('ix_chatbot_documents_document_name'), 'chatbot_documents', ['document_name'], unique=False)
    op.create_index(op.f('ix_chatbot_documents_status'), 'chatbot_documents', ['status'], unique=False)
    op.create_table('chatbot_guardrails',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guardrail_text', sa.String(), nullable=False),
    sa.Column('chatbot_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chatbot_id'], ['chatbot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chatbot_memory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chatbot_id', sa.Integer(), nullable=False),
    sa.Column('creator', sa.String(length=250), nullable=True),
    sa.Column('memory_text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['chatbot_id'], ['chatbot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatbot_memory_chatbot_id'), 'chatbot_memory', ['chatbot_id'], unique=False)
    op.create_index(op.f('ix_chatbot_memory_status'), 'chatbot_memory', ['status'], unique=False)
    op.create_table('chatbot_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chatbot_id', sa.Integer(), nullable=False),
    sa.Column('primary_color', sa.String(length=250), nullable=True),
    sa.Column('chat_header', sa.String(length=250), nullable=True),
    sa.Column('sender_bubble_color', sa.String(length=250), nullable=True),
    sa.Column('receiver_bubble_color', sa.String(length=250), nullable=True),
    sa.Column('receiverTextColor', sa.String(length=250), nullable=True),
    sa.Column('senderTextColor', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['chatbot_id'], ['chatbot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatbot_settings_chatbot_id'), 'chatbot_settings', ['chatbot_id'], unique=False)
    op.create_table('chatbot_suggestion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chatbot_id', sa.Integer(), nullable=False),
    sa.Column('suggestion_text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['chatbot_id'], ['chatbot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatbot_suggestion_chatbot_id'), 'chatbot_suggestion', ['chatbot_id'], unique=False)
    op.create_table('event_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('document_name', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_documents_id'), 'event_documents', ['id'], unique=False)
    op.create_table('event_feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_feedback', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qa_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chatbot_id', sa.Integer(), nullable=True),
    sa.Column('question', sa.String(), nullable=True),
    sa.Column('answer', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('message_id', sa.String(), nullable=True),
    sa.Column('thread_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chatbot_id'], ['chatbot.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    op.create_index(op.f('ix_qa_templates_id'), 'qa_templates', ['id'], unique=False)
    op.create_index(op.f('ix_qa_templates_status'), 'qa_templates', ['status'], unique=False)
    op.create_table('threads',
    sa.Column('thread_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chatbot_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=True),
    sa.Column('title_manual_update', sa.Boolean(), nullable=True),
    sa.Column('setup_project', sa.Boolean(), nullable=True),
    sa.Column('created_timestamp', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_timestamp', sa.TIMESTAMP(), nullable=False),
    sa.Column('agent_generated_prompt', sa.Text(), nullable=True),
    sa.Column('questions_counter', sa.Integer(), nullable=True),
    sa.Column('scaffolding_questions', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['chatbot_id'], ['chatbot.id'], ),
    sa.PrimaryKeyConstraint('thread_id')
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('refresh_token', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invalidated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_id'), 'user_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_user_sessions_refresh_token'), 'user_sessions', ['refresh_token'], unique=True)
    op.create_table('chat_messages',
    sa.Column('message_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('organization_admin_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('ASSISTANT', 'USER', 'TOOL', name='messagerole', native_enum=False), nullable=False),
    sa.Column('message_content', sa.Text(), nullable=True),
    sa.Column('is_image', sa.Boolean(), nullable=True),
    sa.Column('is_revised', sa.Boolean(), nullable=True),
    sa.Column('is_simplify_on', sa.Boolean(), nullable=True),
    sa.Column('images_urls', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created_timestamp', sa.TIMESTAMP(), nullable=False),
    sa.Column('message_uuid', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.thread_id'], ),
    sa.PrimaryKeyConstraint('message_id'),
    sa.UniqueConstraint('message_uuid')
    )
    op.create_table('messages_feedbacks',
    sa.Column('org_admin_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chatbot_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=True),
    sa.Column('chatbot_name', sa.String(length=250), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=True),
    sa.Column('user_name', sa.String(length=250), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('Reviewed', 'Unreviewed', name='feedbackstatus', native_enum=False), nullable=False),
    sa.Column('chatbot_type', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['chatbot_id'], ['chatbot.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.message_uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_feedbacks_chatbot_id'), 'messages_feedbacks', ['chatbot_id'], unique=False)
    op.create_index(op.f('ix_messages_feedbacks_chatbot_name'), 'messages_feedbacks', ['chatbot_name'], unique=False)
    op.create_index(op.f('ix_messages_feedbacks_chatbot_type'), 'messages_feedbacks', ['chatbot_type'], unique=False)
    op.create_index(op.f('ix_messages_feedbacks_message_id'), 'messages_feedbacks', ['message_id'], unique=False)
    op.create_index(op.f('ix_messages_feedbacks_org_admin_id'), 'messages_feedbacks', ['org_admin_id'], unique=False)
    op.create_index(op.f('ix_messages_feedbacks_user_name'), 'messages_feedbacks', ['user_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_feedbacks_user_name'), table_name='messages_feedbacks')
    op.drop_index(op.f('ix_messages_feedbacks_org_admin_id'), table_name='messages_feedbacks')
    op.drop_index(op.f('ix_messages_feedbacks_message_id'), table_name='messages_feedbacks')
    op.drop_index(op.f('ix_messages_feedbacks_chatbot_type'), table_name='messages_feedbacks')
    op.drop_index(op.f('ix_messages_feedbacks_chatbot_name'), table_name='messages_feedbacks')
    op.drop_index(op.f('ix_messages_feedbacks_chatbot_id'), table_name='messages_feedbacks')
    op.drop_table('messages_feedbacks')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_user_sessions_refresh_token'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_table('threads')
    op.drop_index(op.f('ix_qa_templates_status'), table_name='qa_templates')
    op.drop_index(op.f('ix_qa_templates_id'), table_name='qa_templates')
    op.drop_table('qa_templates')
    op.drop_table('event_feedback')
    op.drop_index(op.f('ix_event_documents_id'), table_name='event_documents')
    op.drop_table('event_documents')
    op.drop_index(op.f('ix_chatbot_suggestion_chatbot_id'), table_name='chatbot_suggestion')
    op.drop_table('chatbot_suggestion')
    op.drop_index(op.f('ix_chatbot_settings_chatbot_id'), table_name='chatbot_settings')
    op.drop_table('chatbot_settings')
    op.drop_index(op.f('ix_chatbot_memory_status'), table_name='chatbot_memory')
    op.drop_index(op.f('ix_chatbot_memory_chatbot_id'), table_name='chatbot_memory')
    op.drop_table('chatbot_memory')
    op.drop_table('chatbot_guardrails')
    op.drop_index(op.f('ix_chatbot_documents_status'), table_name='chatbot_documents')
    op.drop_index(op.f('ix_chatbot_documents_document_name'), table_name='chatbot_documents')
    op.drop_index(op.f('ix_chatbot_documents_content_type'), table_name='chatbot_documents')
    op.drop_index('idx_chatbot_id_document_name_status', table_name='chatbot_documents')
    op.drop_index('idx_chatbot_id_document_name', table_name='chatbot_documents')
    op.drop_table('chatbot_documents')
    op.drop_index(op.f('ix_bubble_settings_chatbot_id'), table_name='bubble_settings')
    op.drop_table('bubble_settings')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('securityandlogs')
    op.drop_index(op.f('ix_rbac_id'), table_name='rbac')
    op.drop_table('rbac')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_chatbot_prompt_status'), table_name='chatbot')
    op.drop_index(op.f('ix_chatbot_llm_model_name'), table_name='chatbot')
    op.drop_index(op.f('ix_chatbot_chatbot_type'), table_name='chatbot')
    op.drop_index(op.f('ix_chatbot_chatbot_name'), table_name='chatbot')
    op.drop_table('chatbot')
    op.drop_table('video_tutorials')
    op.drop_table('user_guide')
    op.drop_index(op.f('ix_super_admin_llm_model_name'), table_name='super_admin')
    op.drop_table('super_admin')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_table('file_downloads')
    op.drop_table('faqs')
    op.drop_table('external_links')
    # ### end Alembic commands ###
